name: Deploy to EC2
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
      - uses: actions/checkout@v4

      - name: Create custom directory
        run: sudo mkdir -p ~/custom-directory

      - name: Move files to custom directory
        run: sudo mv * ~/custom-directory

      - name: Verify files in custom directory
        run: ls ~/custom-directory

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/react_google_book_new
            pwd
            git pull origin main
            cd backend
            npm install
            pm2 restart all
            cd ../
            pwd
            npm install
            npm run build
            sudo rm -rf /var/www/html/dist
            sudo cp -R dist /var/www/html
            cd /var/www/html
            pwd
            sudo chown -R www-data:www-data dist
            sudo service nginx restart
